### PR TITLE
Fix invalid character boundary crashes and add basic `proptest` checks

### LINKED ISSUE #5: Use `proptest` for fuzzing
Over at https://github.com/Turbo87/rust-igc I had started to use https://github.com/altsysrq/proptest for some basic input testing. It might be useful to implement something similar here.

### PR DESCRIPTION
**Pull request by Turbo87**
I'd say these `proptest` checks have already paid off... 😅 

Resolves #5

### CODE REVIEW

**Comment by Joey9801** [comment]
So I was aware there are unicode/ascii issues already.
I like the api that comes with the `String`rype, (that you don't get with`[u8]`), though it does open up these kinds of codepoint boundary problems.
The minimal solution to 90% of these problems is to just add a `str::is_ascii()` call at the top level of the API. This would mean the parser rejecting igc files containing unicode, though these files are invalid anyway...

**Comment by Turbo87** [comment]
> This would mean the parser rejecting igc files containing unicode, though these files are invalid anyway...

they are invalid but they are unfortunately very common for pilot name headers, etc.

unfortunately, we can't even assume that everything uses utf8, since some loggers use latin1 instead. I've used `[u8]` in https://github.com/Turbo87/rust-igc, but I think using `&str` might actually make more sense and we should defer the decision on what encoding to use when reading the file to a higher-level parser.

**Comment by Joey9801** [comment]
Perhaps we could allow non-ascii characters in a limited set of places, as a compromise between accepting technically invalid inputs and not having snippets like:
```rust
        if !line.is_char_boundary(7)
            || !line.is_char_boundary(24)
            || !line.is_char_boundary(25)
            || !line.is_char_boundary(30)
            || !line.is_char_boundary(35)
```
After all, if the first 30-something characters of a B record aren't ascii, it's not going to parse regardless of where the character boundaries are.

**Comment by Turbo87** [comment]
@Joey9801 I've changed the code to use `is_ascii()` checks instead and added a dedicated `NonASCIICharacters` error type for this case

**Comment by Turbo87** [comment]
@Joey9801 out of curiosity, why do you squash-merge all the PRs? to me, it usually seems quite useful to keep the history alive in case I ever need to use git bisect to find an issue, at least for larger PRs like this one.

**Pull request merged**
